import type {Compiler, WebpackPluginInstance} from "webpack";
import glob from "fast-glob";
import fs from "fs";

export class ReactGenImageComponentsPlugin implements WebpackPluginInstance {
    private imagePath: string;
    private outputPath: string;

    constructor(imagePath: string, outputPath: string)
    {
        this.imagePath = imagePath;
        this.outputPath = outputPath;
    }

    public apply(compiler: Compiler){
        compiler.hooks.beforeCompile.tap("ImageRecordPlugin", () =>
        {
            const imageFiles = glob.sync(`${this.imagePath}/**/*.{png,jpg,jpeg,gif,svg}`, {
                cwd: process.cwd(),
            });

            const comments = [`// This file is auto-generated by ImageRecordPlugin. manual edits will be lost\n`];

            for (const file of imageFiles)
            {
                const fileName = file.split("/").pop()?.split(".")[0] as string;
                const imageImportString = `import ${fileName} from "../../${file}";`;

                const tsContents = `${imageImportString}

${comments.join("\n").slice(0, -1)}
export const ${fileName}Image = () =>
{
    return (
        <img src={${fileName}} />
    )
}`;

                fs.mkdirSync(this.outputPath, { recursive: true });

                const tsPath = `${this.outputPath}/${fileName}Image.tsx`;
                
                fs.writeFileSync(tsPath, tsContents);
            }
        });
    }
}